"""Update for tasks page and task groups

Revision ID: 1758f2e32cb1
Revises: 
Create Date: 2025-03-05 23:45:27.155295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1758f2e32cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('task_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.drop_column('task_type')
        batch_op.drop_column('points')

    # ### end Alembic commands ###
